[tox]
# Follows what the tox-v3 Docker image sets
minversion =  3.21.4
# You can exclude python versions via TOX_SKIP_ENV:
# Example: TOX_SKIP_ENV='py3(12|13)-.*' tox
# More info: https://doc.wikimedia.org/spicerack/master/development.html#running-tests
envlist = py{311,313}-{lint_unit}
skip_missing_interpreters = True

[tox:jenkins]
# Ensures Jenkins tests Python3.11 as in Bookworm
skip_missing_interpreters = false
envlist = py{311,313}-{lint_unit}

[testenv]
usedevelop = True
basepython =
    py3: python3
    py311: python3.11
    py313: python3.13
description =
    lint_unit: Run ruff, mypy and unit tests
    py3: Python 3
    py311: Python 3.11
    py313: python3.13
    ruff: Fast static analysis
commands =
    lint_unit: mypy --show-error-codes -p cookbooks
    lint_unit: ruff check .
    lint_unit: py.test --strict-markers tests/unit {posargs}
deps =
    lint_unit: .[tests]
