[tox]
# Follows what the tox-v3 Docker image sets
minversion =  3.21.4
envlist = py3-{mypy,ruff,unit}
skip_missing_interpreters = True

[tox:jenkins]
# Ensures Jenkins tests Python3.11 as in Bookworm
skip_missing_interpreters = false
envlist = py311-{mypy,ruff,unit}

[testenv]
usedevelop = True
basepython =
    py3: python3
    py311: python3.11
description =
    mypy: Static analyzer for type annotations
    unit: Unit tests
    py3: Python 3
    py311: Python 3.11
    ruff: Fast static analysis
commands =
    mypy: mypy --show-error-codes -p cookbooks
    ruff: ruff check .
    unit: py.test --strict-markers tests/unit {posargs}
deps =
    ruff: ruff
extras =
    mypy: tests
    unit: tests

[flake8]
max-line-length = 120
statistics = True
